### PR TITLE
Add configs to support docker hub proxy

### LINKED ISSUE #9: Support pull-through proxying of Docker Hub
We'd like to be able to cache things like Redis, Elasticsearch, etc from Docker Hub in our registry, so we can pull from it without network latency, etc.

To do this, we have to update https://github.com/Seneca-CDOT/docker.cdot.systems/blob/main/config/registry/config.yml and add:

```yaml
proxy:
  remoteurl: https://registry-1.docker.io
```

Then we should be able to use `docker pull docker.cdot.systems/redis` or whatever.

### PR DESCRIPTION
**Pull request by TueeNguyen**
Fixes #9 

I followed this guide https://docs.docker.com/registry/recipes/mirror/#run-a-registry-as-a-pull-through-cache

- Add `etc/deamon.json` to specify what registry to mirror 
- Add `proxy.remoteurl`

### CODE REVIEW

**Review by humphd — CHANGES_REQUESTED** [review]
See how GitHub shows the red circle-with-line at the end of your files?  You are missing a newline character.  Every file should end with a newline character, so if any file is concatenated with another, it will start on a new line.

Screen Shot 2022-03-16 at 3 48 28 PM

Please add newlines to both of these.

Looks good otherwise.  I'm excited to try this.

**Comment by TueeNguyen** [comment]
Right, I didn't pay attention to that

**Review by humphd — CHANGES_REQUESTED** [review]
Good stuff.

We also need a `volume` added to our `registry` container to mount this file.  Similar to https://github.com/Seneca-CDOT/docker.cdot.systems/blob/main/docker-compose.yaml#L31, you need to do:

```yml
volumes:
   - /etc/letsencrypt:/etc/letsencrypt
   - ./config/registry/config.yml:/etc/docker/registry/config.yml
   - ./config/etc/daemon.json:/etc/daemon.json
```

**Comment by humphd** [comment]
This got dropped?

**Comment by manekenpix** [comment]
Closed in favour of #12

**Pull request closed without merging**
